// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eeprcwnidolcdammrrek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlcHJjd25pZG9sY2RhbW1ycmVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTgwODUsImV4cCI6MjA3NDU3NDA4NX0.kuBcPic3dwekOhV_TAwLLAHvo-gOa_U5lYmeNuuTTjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});